= JUnit 3 compatibility helper
Patrick Reinhart <https://github.com/reinhapa[@reinhapa]>
:project-full-path: reinhapa/junit-compat
:github-branch: master

image:https://img.shields.io/badge/license-MIT-blue.svg["MIT License", link="https://github.com/{project-full-path}/blob/{github-branch}/LICENSE"]
image:https://img.shields.io/badge/Java-8-blue.svg["Supported Versions", link="https://travis-ci.org/{project-full-path}"]
image:https://img.shields.io/badge/Java-11-blue.svg["Supported Versions", link="https://travis-ci.org/{project-full-path}"]
image:https://img.shields.io/travis/{project-full-path}/{github-branch}.svg["Build Status", link="https://travis-ci.org/{project-full-path}"]
image:https://img.shields.io/maven-central/v/net.reini/junit-compat.svg?label=Maven%20Central["Maven Central", link="https://search.maven.org/search?q=g:%22net.reini%22%20AND%20a:%22junit-compat%22"]
image:https://img.shields.io/codecov/c/github/{project-full-path}/{github-branch}.svg["Code Coverage", link="https://codecov.io/github/{project-full-path}?branch={github-branch}"]
image:https://codecov.io/github/{project-full-path}/branch.svg?branch={github-branch}[codecov.io]

This project contains some of the old JUnit classes that where removed in the newer versions
of JUnit. Using this project besides the actual JUnit library can help migrate to a newer
version more smoothly.

== Enhanced provided helper classes
Additional to the re-added removed JUnit 3 classes there are some additional helper classes
building test suites:

=== CustomTestSuite
Creates a test suite based on a given text file containing all canonical test class names for
the test suite.

=== RepeatFailedTests
Creates a test suite based on a given URIs where the JUnit runner log output is taken to get
the failed tests and build it upon.

=== RecursiveTestSuite
Creates a test suite based on a set of test class files as starting point using their the local
file system location, searching recursively for more test classes that are added to the suite.

== Contribute
Contributions are always welcome. Use https://google.github.io/styleguide/javaguide.html[Google code style format] for your changes. 

== License
This project is licensed under the https://github.com/{project-full-path}/blob/{github-branch}/LICENSE[MIT license]